#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  var Promise, ref$, exec, cat, uid, cwd, _module, join$ = [].join;
  Promise = require('bluebird');
  ref$ = require('shelljs'), exec = ref$.exec, cat = ref$.cat;
  uid = require('uid');
  cwd = process.cwd();
  _module = function(){
    var picNum, process, iface;
    picNum = 0;
    process = function(block, opts){
      var defaultIsSvg, targets;
      defaultIsSvg = {
        cmd: function(block, tmpFile, tmpDir){
          block.to(tmpDir + "/" + tmpFile + ".dia");
          return __dirname + "/node_modules/.bin/ascidia-cli -t svg '" + tmpDir + "/" + tmpFile + ".dia' > /dev/null && cat '" + tmpDir + "/" + tmpFile + ".svg'";
        },
        output: function(tmpFile, tmpDir, output){
          return cat(tmpDir + "/" + tmpFile + ".svg");
        }
      };
      targets = {
        'default': defaultIsSvg,
        svg: defaultIsSvg,
        png: {
          cmd: function(block, tmpFile, tmpDir){
            block.to(tmpDir + "/" + tmpFile + ".dia");
            return __dirname + "/node_modules/.bin/ascidia-cli -t png '" + tmpDir + "/" + tmpFile + ".dia' > /dev/null && cat '" + tmpDir + "/" + tmpFile + ".png' | base64";
          },
          output: function(tmpFile, tmpDir, output){
            return '\n <img class="exemd--diagram exemd--diagram__ascidia" src="data:image/png;base64,' + output + '" /> \n';
          }
        },
        pdf: {
          cmd: function(block, tmpFile, tmpDir){
            var cc;
            block.to(tmpDir + "/" + tmpFile + ".dia");
            cc = [__dirname + "/node_modules/.bin/ascidia-cli -c 20 -t svg '" + tmpDir + "/" + tmpFile + ".dia' > /dev/null", "mkdir -p '" + cwd + "/figures'", "cat '" + tmpDir + "/" + tmpFile + ".svg' | rsvg-convert -z 0.5 -f pdf > '" + cwd + "/figures/f-ascidia-" + picNum + ".pdf'", "echo '" + cwd + "/figures/f-ascidia-" + picNum + ".pdf'"];
            picNum = picNum + 1;
            return join$.call(cc, ' && ');
          },
          output: function(tmpFile, tmpDir, output){
            var fname;
            fname = output;
            return "![](" + fname + ")";
          }
        }
      };
      return opts.pluginTemplate(targets, block, opts);
    };
    iface = {
      process: process
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
