#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  var Promise, ref$, exec, cat, uid, _module;
  Promise = require('bluebird');
  ref$ = require('shelljs'), exec = ref$.exec, cat = ref$.cat;
  uid = require('uid');
  _module = function(){
    var process, iface;
    process = function(block, opts){
      var defaultIsSvg, targets;
      defaultIsSvg = {
        cmd: function(block, tmpFile, tmpDir){
          block.to(tmpDir + "/" + tmpFile + ".dia");
          return __dirname + "/node_modules/.bin/ascidia-cli -t svg " + tmpDir + "/" + tmpFile + ".dia > /dev/null && cat " + tmpDir + "/" + tmpFile + ".svg";
        },
        output: function(tmpFile, tmpDir, output){
          return cat(tmpDir + "/" + tmpFile + ".svg");
        }
      };
      targets = {
        'default': defaultIsSvg,
        svg: defaultIsSvg,
        png: {
          cmd: function(block, tmpFile, tmpDir){
            block.to(tmpDir + "/" + tmpFile + ".dia");
            return __dirname + "/node_modules/.bin/ascidia-cli -t png " + tmpDir + "/" + tmpFile + ".dia > /dev/null && cat " + tmpDir + "/" + tmpFile + ".png | base64";
          },
          output: function(tmpFile, tmpDir, output){
            return '\n <img class="exemd--diagram exemd--diagram__ascidia" src="data:image/png;base64,' + output + '" /> \n';
          }
        }
      };
      return opts.pluginTemplate(targets, block, opts);
    };
    iface = {
      process: process
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
