# Makefile autogenerated by Dyi on March 19, 2015
#
# Main target: all
# Sources:  src/index.js  src/test.js  ./verbfile.js 

.DEFAULT_GOAL := all


.PHONY: c-hhitq6yh
c-hhitq6yh: lib/index.js lib/test.js


.PHONY: c-lpq58nby
c-lpq58nby: readme.md


.PHONY: build
build: c-hhitq6yh c-lpq58nby


.PHONY: test
test: k-a6qb7hoa


.PHONY: docs
docs:


.PHONY: update
update: k-djg917qx


.PHONY: major
major: k-pi69ctmf k-81o69ffs


.PHONY: minor
minor: k-v9vo9gwp k-mvrdp7g0


.PHONY: patch
patch: k-4l72t1bd k-gspjgx0r


.PHONY: prepare
prepare: lib .




.PHONY: k-mwb91pee
k-mwb91pee:  
	cp ./lib/index.js ./index.js


.PHONY: k-wm4baj4f
k-wm4baj4f:  
	make test


.PHONY: all
all: 
	make build 
	make k-mwb91pee 
	make k-wm4baj4f  


.PHONY: k-a6qb7hoa
k-a6qb7hoa:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-djg917qx
k-djg917qx:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-pi69ctmf
k-pi69ctmf:  
	make all


.PHONY: k-81o69ffs
k-81o69ffs:  
	./node_modules/.bin/xyz -i major


.PHONY: k-v9vo9gwp
k-v9vo9gwp:  
	make all


.PHONY: k-mvrdp7g0
k-mvrdp7g0:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-4l72t1bd
k-4l72t1bd:  
	make all


.PHONY: k-gspjgx0r
k-gspjgx0r:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/index.js
	rm -f lib/test.js
	rm -f readme.md




lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

readme.md: ./verbfile.js docs/description.md docs/readme.md 
	./node_modules/.bin/verb

lib: 
	mkdir -p lib

.: 
	mkdir -p .

